Models/Resena.cs
using System.ComponentModel.DataAnnotations;

namespace Final_Cordero_Raura.Models
{
    public class Resena
    {
        [Key]
        public int IdResena { get; set; }
        public string? Titulo { get; set; }
        //[Required]
        //[MaxLength]
        [DataType(DataType.Html)]
        public string? Texto { get; set; }

        public Pelicula? Pelicula { get; set; }
        public int IdPelicula { get; set; }
    }
}

ViewModels/ResenaViewModel.cs
namespace Final_Cordero_Raura.ViewModels
{
    public class ResenaViewModel
    {
        public int IdResena { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public int IdPelicula { get; set; }

        public string NombrePelicula { get; set; }
        public string PosterPelicula { get; set; }
    }
}

Controllers/ResenasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Final_Cordero_Raura.Data;
using Final_Cordero_Raura.Models;
using Final_Cordero_Raura.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Final_Cordero_Raura.Controllers
{
    [Authorize]
    public class ResenasController : Controller
    {
        private readonly Final_Cordero_RauraContext _context;

        public ResenasController(Final_Cordero_RauraContext context)
        {
            _context = context;
        }

        // GET: Resenas//////////////Index (string buscar) es nuevo para el metodo de ordenamiento
        /*Este metodo lo comento porque Index ahora se encuentra
         * combinado con busqueda e impresion de nombre pelicula
        public async Task<IActionResult> Index()
        {
            var resenas = _context.Resena.Include(r => r.Pelicula).ToList();
            return View(resenas);
        }
        */
        public async Task<IActionResult> Index(string buscar, string filtro)
        {
            var resenas = _context.Resena.Include(r => r.Pelicula);

            if (!String.IsNullOrEmpty(buscar))
            {
                resenas = (Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<Resena, Pelicula?>)resenas.Where(s => s.Texto!.Contains(buscar));
            }
            ViewData["FiltroTitulo"] = String.IsNullOrEmpty(filtro) ? "TituloDescendente" : "";
            ViewData["FiltroAnio"] = filtro == "" ? "FechaDescendente" : "";
            switch (filtro)
            {
                case "TituloDescendente":
                    resenas = (Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<Resena, Pelicula?>)resenas.OrderByDescending(resenas => resenas.Titulo);
                    break;
                default:
                    resenas = (Microsoft.EntityFrameworkCore.Query.IIncludableQueryable<Resena, Pelicula?>)resenas.OrderByDescending(resenas => resenas.Titulo);
                    break;

            }


            var resenasConNombrePelicula = await resenas.Select(r => new ResenaViewModel
            {
                IdResena = r.IdResena,
                Titulo = r.Titulo,
                Texto = r.Texto,
                NombrePelicula = r.Pelicula.Nombre, // Agregar el nombre de la película
                PosterPelicula = r.Pelicula.Poster // Agregar el poster de la película
            }).ToListAsync();

            return View(resenasConNombrePelicula);
        }
        

        // GET: Resenas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Resena == null)
            {
                return NotFound();
            }

            var resena = await _context.Resena
                //Aqui modifique segun openIA
                .Include(r => r.Pelicula)
                ////////////////////////////////
                .FirstOrDefaultAsync(m => m.IdResena == id);
            if (resena == null)
            {
                return NotFound();
            }

            return View(resena);
        }

        // GET: Resenas/Create
        public IActionResult Create()
        {
            //Aqui modifico y meto la siguiente linea
            ViewBag.Peliculas = _context.Pelicula.Select(p => new SelectListItem { Value = p.IdPelicula.ToString(), Text = p.Nombre }).ToList();
            ///////////////
            return View();
        }

        // POST: Resenas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdResena,Titulo,Texto,IdPelicula")] Resena resena)
        {
            if (ModelState.IsValid)
            {   //Estas dos lineas de codigo arreglaron el problema con el html
                string htmlContent = Request.Form["Texto"];
                resena.Texto = htmlContent;
                ////////////////////////////
                _context.Add(resena);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //y esta tambien
            ViewData["IdPelicula"] = new SelectList(_context.Pelicula, "IdPelicula", "Titulo", resena.IdPelicula);
            //////////////////
            return View(resena);
        }

        // GET: Resenas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Resena == null)
            {
                return NotFound();
            }

            var resena = await _context.Resena.FindAsync(id);
            if (resena == null)
            {
                return NotFound();
            }
            //Aqui modifico y meto la siguiente linea
            ViewBag.Peliculas = _context.Pelicula.Select(p => new SelectListItem { Value = p.IdPelicula.ToString(), Text = p.Nombre }).ToList();
            ///////////////
            return View(resena);
        }

        // POST: Resenas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdResena,Titulo,Texto,IdPelicula")] Resena resena)
        {
            if (id != resena.IdResena)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //las siguientes dos lineas hacen que sirva guardar el contenido del html
                    string texto = Request.Form["Texto"].ToString();
                    resena.Texto = texto;
                    //////////////////////
                    _context.Update(resena);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResenaExists(resena.IdResena))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //esta liena tambien 
            ViewData["IdPelicula"] = new SelectList(_context.Pelicula, "IdPelicula", "Titulo", resena.IdPelicula);
            //////////////
            return View(resena);
        }

        // GET: Resenas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Resena == null)
            {
                return NotFound();
            }

            var resena = await _context.Resena
                //Aqui modifique segun openIA
                .Include(r => r.Pelicula)
                ////////////////////////////////
                .FirstOrDefaultAsync(m => m.IdResena == id);
            if (resena == null)
            {
                return NotFound();
            }

            return View(resena);
        }

        // POST: Resenas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Resena == null)
            {
                return Problem("Entity set 'Final_Cordero_RauraContext.Resena'  is null.");
            }
            var resena = await _context.Resena.FindAsync(id);
            if (resena != null)
            {
                _context.Resena.Remove(resena);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResenaExists(int id)
        {
          return (_context.Resena?.Any(e => e.IdResena == id)).GetValueOrDefault();
        }
    }
}

Views/Resenas/Create.cshtml
@model Final_Cordero_Raura.Models.Resena

@{
    ViewData["Title"] = "Create";
}
<!--Para que funcione debemos llamar al script del ckeditor-->
<script src="~/lib/ckeditor/ckeditor.js"></script>

<h1>Create</h1>

<h4>Resena</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!--Esto sirve para llamar al editor html ckeditor-->
                <div class="form-group">
                    <label asp-for="Texto" class="control-label"></label>
                    <textarea asp-for="Texto" class="ckeditor"></textarea>
                    @*<textarea class="ckeditor" name="contenido"></textarea>*@
                </div>
            </div>
            @*Esto solo lo comento para probar que sucede si quito el IdPelicula y le dejo solo con Nombre
            <div class="form-group">
                <label asp-for="IdPelicula" class="control-label"></label>
                <input asp-for="IdPelicula" class="form-control" />
                <span asp-validation-for="IdPelicula" class="text-danger"></span>
            </div>
            *@
            @*Aqui agrego un espacio mas donde pruebo si es que sirve que me muestre el nombre de la pelicula en lugar del IdPelicula*@
            <div class="form-group">
                <label asp-for="IdPelicula" class="control-label"></label>
                <select asp-for="IdPelicula" class="form-control" asp-items="@ViewBag.Peliculas"></select>
                <span asp-validation-for="IdPelicula" class="text-danger"></span>
            </div>
            @*/////////////////////////////////////////////*@

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.ckeditor'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

Views/Resenas/Delete.cshtml
@model Final_Cordero_Raura.Models.Resena

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Resena</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Texto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Texto)
        </dd>
        @*Esto está modificado para que ya no muetre Id, sino solo nombre*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pelicula.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pelicula.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdResena" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Resenas/Details.cshtml
@model Final_Cordero_Raura.Models.Resena

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Resena</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Texto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Texto)
        </dd>
        @*Esto está modificado para que ya no muetre Id, sino solo nombre*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pelicula.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pelicula.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdResena">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Resenas/Edit.cshtml
@model Final_Cordero_Raura.Models.Resena

@{
    ViewData["Title"] = "Edit";
}
<!--Para que funcione debemos llamar al script del ckeditor-->
<script src="~/lib/ckeditor/ckeditor.js"></script>

<h1>Edit</h1>

<h4>Resena</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdResena" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="Texto" class="control-label"></label>
                    <textarea asp-for="Texto" class="ckeditor"></textarea>
                    @*<textarea class="ckeditor" name="contenido"></textarea>*@
                </div>
            </div>
            @*Esto solo lo comento para probar que sucede si quito el IdPelicula y le dejo solo con Nombre
            <div class="form-group">
            <label asp-for="IdPelicula" class="control-label"></label>
            <input asp-for="IdPelicula" class="form-control" />
            <span asp-validation-for="IdPelicula" class="text-danger"></span>
            </div>
            *@
            @*Aqui agrego una espacio mas donde pruebo si es que sirve que me muestre el nombre de la pelicula en lugar del IdPelicula*@
            <div class="form-group">
                <label asp-for="IdPelicula" class="control-label"></label>
                <select asp-for="IdPelicula" class="form-control" asp-items="@ViewBag.Peliculas"></select>
                <span asp-validation-for="IdPelicula" class="text-danger"></span>
            </div>
            @*/////////////////////////////////////////////*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.ckeditor'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

Views/Resenas/Index.cshtml
@*@model IEnumerable<Final_Cordero_Raura.Models.Resena>*@
@model IEnumerable<Final_Cordero_Raura.ViewModels.ResenaViewModel>

@{
    ViewData["Title"] = "Reseñas";
}

<h1>Últimas reseñas</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Publica tu reseña</a>
</p>
<form asp-controller="Resenas" asp-action="Index">
    <p>
        Buscar: <input type="text" name="Buscar" class="form-text"/>
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark"/>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-filtro="@ViewData["FiltroTitulo"]">
                    @Html.DisplayNameFor(model => model.Titulo)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Texto)
            </th>
            <th>
                Película
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.Raw(item.Texto)
            </td>
            <td>
                @*Modifiqué los istems debido a compatibilidad con el ResenaViewModel*@
                <img src="@item.PosterPelicula" alt="Poster de la película" width="100" height="150" />
                @Html.DisplayFor(modelItem => item.NombrePelicula)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdResena">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.IdResena">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.IdResena">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>