Models/Pelicula.cs
using System.ComponentModel.DataAnnotations;

namespace Final_Cordero_Raura.Models
{
    public class Pelicula
    {
        [Key]
        public int IdPelicula { get; set; }
        public string? Nombre { get; set; }
        [DataType(DataType.Html)]
        public string? Descripcion { get; set; }
        public string? Genero { get; set; }
        public int anio { get; set; }
        public string? Poster { get; set; }

        public List<Resena>? Resenas { get; set; }
    }
}

Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Final_Cordero_Raura.Data;
using Final_Cordero_Raura.Models;
using Microsoft.AspNetCore.Authorization;

namespace Final_Cordero_Raura.Controllers
{
    [Authorize]
    public class PeliculasController : Controller
    {
        private readonly Final_Cordero_RauraContext _context;

        public PeliculasController(Final_Cordero_RauraContext context)
        {
            _context = context;
        }

        // GET: Peliculas
        public async Task<IActionResult> Index(string buscar, string filtro)
        {
            var peliculas = from pelicula in _context.Pelicula select pelicula;
            if (!String.IsNullOrEmpty(buscar))
            {
                peliculas = peliculas.Where(s => s.Nombre!.Contains(buscar) || s.Genero!.Contains(buscar));
            }

            ViewData["FiltroNombre"] = String.IsNullOrEmpty(filtro) ? "NombreDescendente" : "";
            ViewData["FiltroAnio"] = filtro == "" ? "FechaDescendente" : "";
            switch (filtro)
            {
                case "NombreDescendente":
                    peliculas = peliculas.OrderByDescending(resenas => resenas.Nombre);
                    break;
                case "FechaDescendente":
                    peliculas = peliculas.OrderByDescending(resenas => resenas.anio);
                    break;
                default:
                    peliculas = peliculas.OrderBy(resenas => resenas.Nombre);
                    break;

            }

            return View(await peliculas.ToListAsync());
        }


        // GET: Peliculas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pelicula == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Pelicula
                .FirstOrDefaultAsync(m => m.IdPelicula == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // GET: Peliculas/Create
        public IActionResult Create()
        {
            //Aqui modifico y meto la siguiente linea
            ViewBag.Resenas = _context.Resena.Select(p => new SelectListItem { Value = p.IdPelicula.ToString(), Text = p.Titulo }).ToList();
            ///////////////
            return View();
        }

        // POST: Peliculas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPelicula,Nombre,Descripcion,Genero,anio,Poster")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                //Estas dos lineas de codigo arreglaron el problema con el html
                string htmlContent = Request.Form["Descripcion"];
                pelicula.Descripcion = htmlContent;
                ////////////////////////////
                _context.Add(pelicula);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //y esta tambien
            //ViewData["IdPelicula"] = new SelectList(_context.Pelicula, "IdPelicula", "Descripcion", pelicula.IdPelicula);

            //////////////////
            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pelicula == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Pelicula.FindAsync(id);
            if (pelicula == null)
            {
                return NotFound();
            }
            //Aqui modifico y meto la siguiente linea
            ViewBag.Resenas = _context.Resena.Select(p => new SelectListItem { Value = p.IdPelicula.ToString(), Text = p.Titulo }).ToList();
            ///////////////
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPelicula,Nombre,Descripcion,Genero,anio,Poster")] Pelicula pelicula)
        {
            if (id != pelicula.IdPelicula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //las siguientes dos lineas hacen que sirva guardar el contenido del html
                    var texto = Request.Form["Descripcion"].ToString();
                    pelicula.Descripcion = texto;
                    //////////////////////
                    _context.Update(pelicula);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeliculaExists(pelicula.IdPelicula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //NO SE QUE HICE AQUI, MODIFICAR POR SI ACASO
            //esta liena tambien 
            ViewData["Descripcion"] = new SelectList(_context.Pelicula, "Genero", "Descripcion", pelicula.Descripcion);
            //////////////
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pelicula == null)
            {
                return NotFound();
            }

            var pelicula = await _context.Pelicula
                //Aqui modifique segun openIA//modificado como tres veces, puede que este mal
                .Include(r => r.Resenas)
                ////////////////////////////////
                .FirstOrDefaultAsync(m => m.IdPelicula == id);
            if (pelicula == null)
            {
                return NotFound();
            }

            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pelicula == null)
            {
                return Problem("Entity set 'Final_Cordero_RauraContext.Pelicula'  is null.");
            }
            var pelicula = await _context.Pelicula.FindAsync(id);
            if (pelicula != null)
            {
                _context.Pelicula.Remove(pelicula);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeliculaExists(int id)
        {
          return (_context.Pelicula?.Any(e => e.IdPelicula == id)).GetValueOrDefault();
        }
    }
}

Views/Peliculas/Create.cshtml
@model Final_Cordero_Raura.Models.Pelicula

@{
    ViewData["Title"] = "Create";
}
<!--Para que funcione debemos llamar al script del ckeditor-->
<script src="~/lib/ckeditor/ckeditor.js"></script>

<h1>Create</h1>

<h4>Pelicula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <!--Esto sirve para llamar al editor html ckeditor-->
            <div class="form-group">
                <!--Esto sirve para llamar al editor html ckeditor-->
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <textarea asp-for="Descripcion" class="ckeditor"></textarea>
                    @*<textarea class="ckeditor" name="contenido"></textarea>*@
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="anio" class="control-label"></label>
                <input asp-for="anio" class="form-control" />
                <span asp-validation-for="anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.ckeditor'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

Views/Peliculas/Delete.cshtml
@model Final_Cordero_Raura.Models.Pelicula

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.anio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poster)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPelicula" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Peliculas/Details.cshtml
@model Final_Cordero_Raura.Models.Pelicula

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pelicula</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.anio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poster)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdPelicula">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Peliculas/Edit.cshtml
@model Final_Cordero_Raura.Models.Pelicula

@{
    ViewData["Title"] = "Edit";
}
<!--Para que funcione debemos llamar al script del ckeditor-->
<script src="~/lib/ckeditor/ckeditor.js"></script>

<h1>Edit</h1>

<h4>Pelicula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPelicula" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <textarea asp-for="Descripcion" class="ckeditor"></textarea>
                    @*<textarea class="ckeditor" name="contenido"></textarea>*@
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="anio" class="control-label"></label>
                <input asp-for="anio" class="form-control" />
                <span asp-validation-for="anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.ckeditor'))
            .catch(error => {
                console.error(error);
            });
    </script>
}

Views/Peliculas/Index.cshtml
@model IEnumerable<Final_Cordero_Raura.Models.Pelicula>

@{
    ViewData["Title"] = "Index";
}

<h1>Peliculas disponibles</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Agregar película</a>
</p>
<form asp-controller="Peliculas" asp-action="Index">
    <p>
        Buscar: <input type="text" name="Buscar" class="form-text" />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-filtro="@ViewData["FiltroNombre"]">
                    @Html.DisplayNameFor(model => model.Nombre)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-filtro="@ViewData["FiltroFecha"]">
                    @Html.DisplayNameFor(model => model.anio)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.anio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.Raw(item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.anio)
            </td>
            <td>
                    <!--Aqui cambie para que muestre foto-->
                    <img src="@item.Poster" alt="@item.Nombre" style="max-width: 200px;max-height: 320px;" />
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdPelicula">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdPelicula">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdPelicula">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>